### ISSUE TITLE
Missing Cargo.lock

### ISSUE THREAD

**Issue by autrimpo** [dudik/adblock-rust-server#1]
As an application meant to be deployed, the repository should also contain the cargo lockfile, see [the docs](https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html).

In addition, consider tagging specific releases (I see there is a 0.3.0 in the cargo file) - both of these will ease packaging for distributions.

**Comment by dudik** [comment]
I added the lockfile and removed if from .gitignore. I also created a new release on Github. Just to be sure, is that what you meant by "consider tagging specific releases", right? Thank you.

**Comment by autrimpo** [comment]
Indeed, a git tag that can be referenced in a package definiton.
